language: php

services:
  - docker

php:
  - 7.2
  - 7.3
  - 7.4

before_install:
  - cd src
  - cp .env.example .env

before_script:
  - cd ..
  - cp init-db.env.example init-db.env
  - docker network create traefik # in place of Traefik container

script:
  - shellcheck setup.sh
  - ./setup.sh # builds image, generates laravel key, migrates DB
  - docker ps | grep -q laraview
  - docker ps | grep -q laraview-db
  - ./src/vendor/bin/phplint ./src --exclude=vendor