services:
  glass:
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.glass.rule=Host(`glass.localhost`)'
    networks:
      - traefik
    depends_on:
      glass-db:
        condition: service_started
    volumes:
      - ./src:/var/www/html
  glass-db:
    image: 'mariadb:11.4.3'
    restart: always
    volumes:
      - glass-db:/var/lib/mysql
    environment:
      MARIADB_DATABASE: glass
      MARIADB_ROOT_PASSWORD: password
      MARIADB_USER: glass
      MARIADB_PASSWORD: password
      MARIADB_AUTO_UPGRADE: 1
    networks:
      - glass

volumes:
  glass-db:
    name: glass-db

networks:
  traefik:
    name: traefik
    external: true
