version: "3.8"
services:
  glass:
    build: .
    restart: always
    networks:
      - traefik
      - glass
    labels:
      - traefik.enable=true
    env_file:
      - src/.env
    depends_on:
      - glass-db
  glass-db:
    image: 'mariadb:10.8.2'
    restart: always
    volumes:
      - database-data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - glass

volumes:
  database-data:
    driver: local

networks:
  traefik:
    name: traefik
  glass:
    name: glass
