services:
  glass:
    build: .
    restart: unless-stopped
    networks:
      - traefik
      - glass
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.port=80
    env_file:
      - src/.env
    depends_on:
      - glass-db
      - glass-db-replica
  glass-db:
    image: 'bitnami/mariadb:10.6.4'
    restart: unless-stopped
    volumes:
      - database-data:/bitnami/mariadb
    environment:
      - MARIADB_REPLICATION_MODE=master
      - MARIADB_SKIP_TEST_DB=yes
    env_file:
      - database.env
    networks:
      - glass
    labels:
      - traefik.enable=false
  glass-db-replica:
    image: 'bitnami/mariadb:10.6.4'
    restart: unless-stopped
    depends_on:
      - glass-db
    environment:
      - MARIADB_REPLICATION_MODE=slave
      - MARIADB_MASTER_HOST=glass-db
    env_file:
      - database.env
    networks:
      - glass
    labels:
      - traefik.enable=false

volumes:
  database-data:
    driver: local

networks:
  traefik:
    name: traefik
  glass:
    name: glass
