services:
  glass:
    build:
      args:
        PROD: true
    ports:
      - 8140:80
    mem_limit: '1024m'
    healthcheck:
      test: ['CMD', 'curl', '--silent', '--output', '/dev/null', '--show-error', '--fail', 'http://localhost/up']
      start_period: 10s
      start_interval: 1s
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./src/storage/app/public:/var/www/html/public/storage
