services:
  glass:
    build: .
    restart: always
    networks:
      - traefik
      - glass
    labels:
      - traefik.enable=true
    env_file:
      - src/.env
  glass-db:
    image: 'mariadb:11.3.2'
    restart: always
    labels:
      - 'traefik.docker.network=traefik-glass'
    volumes:
      - database-data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - glass

volumes:
  database-data:
    driver: local

networks:
  traefik-glass:
    external: true
  glass:
