version: "3.8"
services:
  glass:
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.50"
          memory: "512M"
        reservations:
          cpus: "0.25"
          memory: "128M"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.http.routers.glass.rule=Host(`blog.justinpaulhammond.com`) || Host(`www.blog.justinpaulhammond.com`)"
      - "traefik.http.routers.glass.tls=true"
      - "traefik.http.routers.glass.tls.certresolver=letsencrypt"
    volumes:
      - ./src/storage/logs:/var/www/html/storage/logs
      - ./src/storage/app/public:/var/www/html/public/storage
  glass-db:
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "512M"
        reservations:
          cpus: "0.25"
          memory: "128M"
    healthcheck:
      test: ["CMD", "mysql", "-u${MARIADB_USER}", "-p${MARIADB_PASSWORD}", "-e", "show databases;"]
      interval: 30s
      timeout: 10s
      retries: 3
