name: build

on: [push, pull_request]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      # TODO: Once GitHub Actions runs `docker-compose` v2, remove this step
      - name: Setup Docker Compose v2
        run: |
          curl -LJs https://github.com/docker/compose/releases/download/v2.1.0/docker-compose-linux-x86_64 > /usr/local/bin/docker-compose
      - name: Setup Traefik
        run: docker network create traefik
      - name: Setup Docker container
        run: |
          cp src/.env-example src/.env
          cp database.env-example database.env
          docker-compose -f docker-compose.yml -f docker-compose-prod.yml up -d
          docker ps | grep -q glass-glass-1
          docker ps | grep -q glass-glass-2
          docker ps | grep -q glass-glass-db-1
          docker ps | grep -q glass-glass-db-replica-1
      - name: Migrate and seed database
        run: |
          sleep 15
          docker exec -t glass-glass-1 php artisan migrate
          docker exec -t glass-glass-1 php artisan db:seed
  lint-php:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
      - name: Install Composer
        run: cd src && composer self-update
      - name: Install Dependencies
        run: cd src && composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Lint
        run: cd src && composer lint
  lint-sass:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install dependencies
        run: cd src && npm install
      - name: Run SASS lint
        run: cd src && npm run lint
  deploy:
    needs: ["docker", "lint-php", "lint-sass"]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Harvey
        if: github.ref == 'refs/heads/main'
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_type: "json-extended"
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          data: '{ "pipeline": "deploy", "compose" : "docker-compose.yml -f docker-compose-prod.yml" }'
