name: build

on:
  push:
    tags:
      - '*'
  workflow_dispatch: ~

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - name: Sign into Docker
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build Docker image
        run: docker build -t justintime50/glass:${GITHUB_REF##*/v} --build-arg PROD=true --platform linux/amd64,linux/arm64 .
      - name: Push image to Registry
        run: docker push justintime50/glass:${GITHUB_REF##*/v}
