name: ci

on: [push, pull_request]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
      - run: docker network create traefik
      - name: Setup Docker container
        run: |
          cd src
          cp .env-example .env
          just setup
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Lint project
        run: |
          cd src
          just install lint
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        phpversion: ['8.2', '8.3', '8.4']
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.phpversion }}
          coverage: xdebug
      - run: docker network create traefik
      - name: Install Dependencies
        run: |
          cd src
          cp .env-example .env
          just setup
      - name: Run tests
        run: |
          cd src
          just coverage
  coverage:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: xdebug
      - name: Generate coverage report
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd src
          just install coverage
          ./bin/php-coveralls --coverage_clover=build/logs/clover.xml -v
