name: latest

on:
  push:
    branches:
      - main

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - name: Sign into Docker
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build latest Docker image and push to Docker Hub
        run: docker build -t justintime50/glass --build-arg PROD=true --platform linux/amd64,linux/arm64 .
      - name: Push image to Registry
        run: docker push justintime50/glass
